##############################################################
#
# This file includes all the test targets as well as all the
# non-default build rules and test recipes.
#
##############################################################

###### Additional includes that are specific to this directory ######

# Placeholder for additional include files.


##############################################################
#
# Test targets
#
##############################################################

###### Place all generic definitions here ######

# This defines tests which run tools of the same name.  This is simply for convenience to avoid
# defining the test name twice (once in TOOL_ROOTS and again in TEST_ROOTS).
# Tests defined here should not be defined in TOOL_ROOTS and TEST_ROOTS.
TEST_TOOL_ROOTS := 

# This defines the tests to be run that were not already defined in TEST_TOOL_ROOTS.
TEST_ROOTS := 

# This defines the tools which will be run during the the tests, and were not already defined in
# TEST_TOOL_ROOTS.
TOOL_ROOTS := cmp_hook fuzz_cfg IFR_BasicBlock

# This defines the static analysis tools which will be run during the the tests. They should not
# be defined in TEST_TOOL_ROOTS. If a test with the same name exists, it should be defined in
# TEST_ROOTS.
# Note: Static analysis tools are in fact executables linked with the Pin Static Analysis Library.
# This library provides a subset of the Pin APIs which allows the tool to perform static analysis
# of an application or dll. Pin itself is not used when this tool runs.
SA_TOOL_ROOTS :=

# This defines all the applications that will be run during the tests.
APP_ROOTS := 

# This defines any additional object files that need to be compiled.
OBJECT_ROOTS := 

# This defines any additional dlls (shared objects), other than the pintools, that need to be compiled.
DLL_ROOTS :=

# This defines any static libraries (archives), that need to be built.
LIB_ROOTS := 

###### Place architecture-specific definitions here ######

# Place ia32-specific definitions here if they apply to all supported operating systems.
ifeq ($(TARGET),ia32)
    TOOL_CXXFLAGS += -m32 
    LIBDFT_INC_PATH	= $(realpath ../src32/)
    LIBDFT_PATH	= $(realpath ../src32/obj-ia32/)
endif

# Place intel64-specific definitions here if they apply to all supported operating systems.
ifeq ($(TARGET),intel64)
	TOOL_CXXFLAGS +=
    LIBDFT_INC_PATH	= $(realpath ../src/)
    LIBDFT_PATH	= $(realpath ../src/obj-intel64/)
endif

##############################################################
#
# Test recipes
#
##############################################################

###### Finalize sanity here ######

# This section contains recipes for tests other than the default.
# See makefile.default.rules for the default test rules.
# All tests in this section should adhere to the naming convention: <testname>.test


##############################################################
#
# Build rules
#
##############################################################

# This section contains the build rules for all binaries that have special build rules.
# See makefile.default.rules for the default build rules.

###### Special tools' build rules ######

LOGGING_FLAGS = -DNO_PINTOOL_LOG
TOOL_CXXFLAGS += $(LOGGING_FLAGS) -I$(LIBDFT_INC_PATH) -L$(LIBDFT_PATH) -L ./deps/
TOOL_LIBS += -L$(LIBDFT_PATH) -ldft
CXXFLAGS = ""
SCRIPT_DIR=./scripts/
INFO_DIR=$(SCRIPT_DIR)info/
PIN_TOOL_DIR=./pin_tool/

.PHONY: collector test_cmp test_cfg test_all clear_wrong_so clean

INPUT_FILE=$(OBJDIR)cur_input
$(OBJDIR)hashtest: hashtest.cpp sha256.c
	g++ -I ./deps/ $^ -o $(OBJDIR)/hashtest
	cp cur_input $(INPUT_FILE)

clear_wrong_so: 
	rm -rf $(OBJDIR)fuzz_cfg.so $(OBJDIR)IFR_BasicBlock.so

$(OBJDIR)fuzz_cfg.so: $(OBJDIR)fuzz_cfg.o $(OBJDIR)IFR_BasicBlock.o
	$(LINKER) $(TOOL_LDFLAGS) $(LINK_EXE)$@ $^ $(TOOL_LPATHS) $(TOOL_LIBS)

collector: clear_wrong_so $(OBJDIR)cmp_hook.so $(OBJDIR)fuzz_cfg.so
	cp $(OBJDIR)cmp_hook.so $(PIN_TOOL_DIR)cmp_hook.so
	cp $(OBJDIR)fuzz_cfg.so $(PIN_TOOL_DIR)fuzz_cfg.so

test_cmp: $(PIN_TOOL_DIR)cmp_hook.so $(OBJDIR)hashtest
	sudo sh -c "echo 0 > /proc/sys/kernel/randomize_va_space"
	rm -rf $(INFO_DIR)cmp_hook.info
	$(PIN) -t $< -- $(word 2, $^) $(INPUT_FILE) 

test_cfg: $(PIN_TOOL_DIR)fuzz_cfg.so $(OBJDIR)hashtest
	sudo sh -c "echo 0 > /proc/sys/kernel/randomize_va_space"
	rm -rf $(INFO_DIR)fuzz_cfg.info
	$(PIN) -t $< -- $(word 2, $^) $(INPUT_FILE)

test_all: test_cmp test_cfg

clean_all:
	rm -rf $(OBJDIR)/*
	rm -rf $(PIN_TOOL_DIR)/*
	rm -rf $(INFO_DIR)/*.info